### PR TITLE
feat: add caching system

### LINKED ISSUE #28: Implement a flexible cache system
Cache system should also be flexible for it's use in Pacstall's debug mode.

**Database requirements**
- Repo information including:
    - URL
    - Last update
    - List of packages
    - Preference order
- Pacscript information, including:
    - Name
    - Description
    - Homepage
    - Repology
    - Repository version (from last update)
    - Installed version
    - Auto/Manual
    - Dependencies (both apt's and pacstall's)
    - Optional dependencies (both apt's and pacstall's)
    - License (Requested [here](https://github.com/pacstall/libpacstall/pull/29#issuecomment-1141455042) by @Henryws)

**Other requirements**
- Source x Installed correlation
- Methods for safely adding and updating entries

### PR DESCRIPTION
**Pull request by wizard-28**
Closes #28 

### Repository (Source) table
- [x] URL
- [x] Last update
- [x] Preference order
 
### Pacscript table

- [x] Name
- [x] Homepage
- [x] Repology
- [x] repository
- [x] Installed size
- [x] Download Size
- [x] Description
- [ ] License
- [x] version
- [x] maintainer
- [x] Auto/Manual
- [x] APT dependencies
- [x] Pacstall dependencies
- [x] APT optional dependencies
- [x] Pacstall optional dependencies
- [x] is_installed

### CODE REVIEW

**Review by 0oAstro — APPROVED** [review]

**Comment by Elsie19** [comment]
Since a PKGBUILD will be compatible with 2.0.0 Pacscript, should this caching system also log what license a package is?

Also, other keys should probably be added ([reference](https://gitlab.archlinux.org/pacman/pacman/raw/master/proto/PKGBUILD.proto)).

**Review by Elsie19 — COMMENTED** [review]
Check codacy also

**Comment by wizard-28** [comment]
> Check codacy also

Checked those, nothing can be done. I'll exclude the test directory from Codacy tests.

**Comment by wizard-28** [comment]
Closing this as there will be a Rust implementation.

**Pull request closed without merging**
