### PR TITLE
feat: add initial config parser module

### LINKED ISSUE #6: Setup tests and coverage
Use the [pytest](https://docs.pytest.org/en/7.1.x/) framework for writing tests.

### LINKED ISSUE #11: Add a `jobs` variable to config's settings
This integer would be used instead of relying on `nproc` for operations such as `make` (or any internal python operation). So that people can configure the core count themselves. If it's not set then default to `nproc`.

Example:
```toml
[settings]
jobs = 4
```

### LINKED ISSUE #12: Add `editor` variable to the config's settings
This `editor` variable will replace the `PACSTALL_EDITOR` environment variable.

Example:
```toml
[settings]
editor = "nvim"
```

### PR DESCRIPTION
**Pull request by wizard-28**
Closes #11
Closes #12 
Closes #6

### CODE REVIEW

**Review by D-Brox — DISMISSED** [review]

**Comment by D-Brox** [comment]
Had to search pytest's docs, but seems ok

**Comment by wizard-28** [comment]
@D-Brox So... only this? No other config settings? I think we need a `repository` array, but I can't work on it with an issue, so make the issue detailing it.

**Comment by wizard-28** [comment]
> @D-Brox So... only this? No other config settings? I think we need a `repository` array, but I can't work on it with an issue, so make the issue detailing it.

I guess I'll do it in another PR.

**Comment by D-Brox** [comment]
> @D-Brox So... only this? No other config settings? I think we need a `repository` array, but I can't work on it with an issue, so make the issue detailing it.

I think the repository variable will have to be a dict if we want to implement repo names

**Pull request merged**
